#!/usr/bin/env node
/* Writes config.js from env (.env.local / .env / process.env) for the static PWA. */
var fs = require("fs");
var path = require("path");

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  var text = fs.readFileSync(filePath, "utf8");
  text.split(/\r?\n/).forEach(function (line) {
    var trimmed = line.trim();
    if (!trimmed || trimmed.charAt(0) === "#") return;
    var eq = trimmed.indexOf("=");
    if (eq < 1) return;
    var key = trimmed.slice(0, eq).trim();
    var val = trimmed.slice(eq + 1).trim();
    if (
      (val.charAt(0) === '"' && val.charAt(val.length - 1) === '"') ||
      (val.charAt(0) === "'" && val.charAt(val.length - 1) === "'")
    ) {
      val = val.slice(1, -1);
    }
    if (process.env[key] == null || process.env[key] === "") {
      process.env[key] = val;
    }
  });
}

var root = path.join(__dirname, "..");
loadEnvFile(path.join(root, ".env.local"));
loadEnvFile(path.join(root, ".env"));

var url =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  "";
var anon =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.SUPABASE_ANON_KEY ||
  "";

var out =
  "/* Generated by scripts/write-config.js — do not edit by hand */\n" +
  "window.COIN_CHART_CONFIG = " +
  JSON.stringify({ supabaseUrl: url, supabaseAnonKey: anon }, null, 2) +
  ";\n";

fs.writeFileSync(path.join(root, "config.js"), out);
console.log(
  "Wrote config.js (" +
    (url ? "Supabase URL set" : "no Supabase URL") +
    ", " +
    (anon ? "anon key set" : "no anon key") +
    ")"
);
